services:
  chibako:
    build: .
    restart: unless-stopped
    environment:
      - DATA_DIR=/app/data
      - SITE_NAME=${SITE_NAME:-Chibako}
    volumes:
      - ${CHIBAKO_DATA_VOLUME:-./data}:/app/data
    networks:
      - chibako
    ports:
      - "127.0.0.1:${CHIBAKO_PORT:-3000}:3000"

networks:
  chibako:
